name: CI

on:
  pull_request:

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/nx-main.yml
    with:
      final-commands: |
        npx nx affected -t lint

  check:
    name: Check
    uses: ./.github/workflows/nx-main.yml
    with:
      final-commands: |
        npx nx affected -t test

  e2e:
    name: E2E
    uses: ./.github/workflows/nx-main.yml
    with:
      final-commands: |
        npx nx affected -t e2e