name: Docs

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Docs
    uses: ./.github/workflows/nx-main.yml
    with:
      final-commands: |
        npx nx graph --file=docs/dependency-graph/index.html
        poetry run mkdocs gh-deploy
